sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - stable

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true
  allow_failures:
    - node_js: stable

install:
  # Check the size of caches
  - du -sh ./node_modules ./test/tmp/deps/node_modules || true
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  - npm install -g npm@latest
  # Instal npm dependecies and ensure that npm cache is not stale
  - ./scripts/generator-install-dependencies.sh

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install sass
  - npm install -g gulp

script: gulp
